name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Regenerate README.md
      run: swift readme_gen.swift > README.md
    - name: Push and Save
      run: |
        git add README.md
        git commit -m "Regenerate README file."
        git push
